/*
 * Class : DIT/FT/1B/03
 * Admission Number : p2037084
 * Name : Tan Jing Wen
 */
package JPRG2;

import javax.swing.JOptionPane;
import java.io.* ;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author jw
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() throws IOException{
        initComponents();
        user.requestFocus();
    }

    // create EventManagement object
    EventManagement event = new EventManagement();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeofuser = new javax.swing.ButtonGroup();
        typeofevent = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        admin = new javax.swing.JRadioButton();
        user = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        display = new javax.swing.JScrollPane();
        resultdisplay = new javax.swing.JTextArea();
        result = new javax.swing.JLabel();
        adminpane = new javax.swing.JPanel();
        namelabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        organizerlabel = new javax.swing.JLabel();
        organizer = new javax.swing.JTextField();
        feeslabel = new javax.swing.JLabel();
        fees = new javax.swing.JTextField();
        datentimelabel = new javax.swing.JLabel();
        datentime = new javax.swing.JTextField();
        online = new javax.swing.JCheckBox();
        facetoface = new javax.swing.JCheckBox();
        addbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        namelabel1 = new javax.swing.JLabel();
        nametosearch = new javax.swing.JTextField();
        searchbynamebutton = new javax.swing.JButton();
        registerbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        feeslabel1 = new javax.swing.JLabel();
        feestosearch = new javax.swing.JTextField();
        searchbyfeesbutton = new javax.swing.JButton();
        displaybutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(1048, 700));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("-- EVENT MANAGEMENT SYSTEM --");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        typeofuser.add(admin);
        admin.setText("ADMINISTRATOR");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        typeofuser.add(user);
        user.setSelected(true);
        user.setText("NORMAL USER");
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        jLabel1.setText("USER TYPE :");

        display.setForeground(new java.awt.Color(153, 153, 255));

        resultdisplay.setEditable(false);
        resultdisplay.setColumns(20);
        resultdisplay.setRows(5);
        display.setViewportView(resultdisplay);

        result.setText("RESULT :");

        adminpane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        namelabel.setText("NAME :");

        organizerlabel.setText("ORGANIZER :");

        feeslabel.setText("FEES :");

        datentimelabel.setText("DATE & TIME :");

        typeofevent.add(online);
        online.setText("online");
        online.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineActionPerformed(evt);
            }
        });

        typeofevent.add(facetoface);
        facetoface.setText("face-to-face");
        facetoface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facetofaceActionPerformed(evt);
            }
        });

        addbutton.setBackground(new java.awt.Color(153, 255, 153));
        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        deletebutton.setBackground(new java.awt.Color(255, 153, 153));
        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminpaneLayout = new javax.swing.GroupLayout(adminpane);
        adminpane.setLayout(adminpaneLayout);
        adminpaneLayout.setHorizontalGroup(
            adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminpaneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminpaneLayout.createSequentialGroup()
                        .addComponent(feeslabel)
                        .addGap(98, 98, 98)
                        .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminpaneLayout.createSequentialGroup()
                                .addComponent(online, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(facetoface)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(adminpaneLayout.createSequentialGroup()
                                .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(fees)))
                    .addGroup(adminpaneLayout.createSequentialGroup()
                        .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(organizerlabel)
                            .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datentimelabel))
                        .addGap(34, 34, 34)
                        .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(organizer)
                            .addComponent(datentime))))
                .addContainerGap())
        );
        adminpaneLayout.setVerticalGroup(
            adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminpaneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizerlabel)
                    .addComponent(organizer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datentimelabel)
                    .addComponent(datentime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feeslabel)
                    .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(online, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facetoface))
                .addGap(15, 15, 15)
                .addGroup(adminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton)
                    .addComponent(deletebutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        namelabel1.setText("NAME :");

        searchbynamebutton.setBackground(new java.awt.Color(255, 153, 102));
        searchbynamebutton.setText("SEARCH BY NAME");
        searchbynamebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbynamebuttonActionPerformed(evt);
            }
        });

        registerbutton.setBackground(new java.awt.Color(255, 255, 102));
        registerbutton.setText("REGISTER");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(namelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(searchbynamebutton)
                        .addGap(18, 18, 18)
                        .addComponent(registerbutton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nametosearch))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel1)
                    .addComponent(nametosearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbynamebutton)
                    .addComponent(registerbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("ADD / DELETE EVENT");

        jLabel7.setText("SEARCH EVENT");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        feeslabel1.setText("FEES :");

        searchbyfeesbutton.setBackground(new java.awt.Color(255, 153, 102));
        searchbyfeesbutton.setText("SEARCH BY FEES");
        searchbyfeesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbyfeesbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(feeslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(searchbyfeesbutton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(feestosearch))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feeslabel1)
                    .addComponent(feestosearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchbyfeesbutton)
                .addContainerGap())
        );

        displaybutton.setBackground(new java.awt.Color(102, 153, 255));
        displaybutton.setText("DISPLAY");
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });

        resetbutton.setBackground(new java.awt.Color(153, 255, 153));
        resetbutton.setText("RESET");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        exitbutton.setBackground(new java.awt.Color(255, 102, 102));
        exitbutton.setText("EXIT");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(admin)
                        .addGap(39, 39, 39)
                        .addComponent(user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(display))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user)
                    .addComponent(admin)
                    .addComponent(jLabel1)
                    .addComponent(exitbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result)
                    .addComponent(jLabel2)
                    .addComponent(displaybutton)
                    .addComponent(resetbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adminpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


// checkbox for "online"
    private void onlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineActionPerformed
        
    }//GEN-LAST:event_onlineActionPerformed

// radiobutton for "normal user"
    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // to disable add and delete functions
        addbutton.setEnabled(false);
        deletebutton.setEnabled(false);
        registerbutton.setEnabled(true);
        name.setEnabled(false);
        organizer.setEnabled(false);
        datentime.setEnabled(false);
        fees.setEnabled(false);
        online.setEnabled(false);
        facetoface.setEnabled(false);
    }//GEN-LAST:event_userActionPerformed

// search button by "name"   
    private void searchbynamebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbynamebuttonActionPerformed
        // check if event name input is empty
        if ((nametosearch.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "EVENT NAME cannot be null ! Please key in again.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String searchname = nametosearch.getText();
            try {
                resultdisplay.setText(event.Search1(searchname));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Unknown error while displaying search result. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_searchbynamebuttonActionPerformed

// search button by "fees"
    private void searchbyfeesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbyfeesbuttonActionPerformed
        boolean error = false;
        double searchfees = 0.0;
        // check if event fees input is empty
        if ((feestosearch.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "EVENT FEES cannot be null ! Please key in again.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String searchfeest = feestosearch.getText();
            // check if event fees input is number
            try {
                searchfees = Double.parseDouble(searchfeest);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "EVENT FEES is not a number ! Please key in again.", "Error", JOptionPane.ERROR_MESSAGE);
                error = true;
            }

            if (error == false) {
                try {
                    resultdisplay.setText(event.Search2(searchfees));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Unknown error while displaying search result. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_searchbyfeesbuttonActionPerformed

// register button 
    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // check if event name input is empty
        if ((nametosearch.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "EVENT NAME cannot be null ! Please key in again.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String registername = nametosearch.getText();
            try {
                resultdisplay.setText(event.Register(registername));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Unknown error while displaying search result. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_registerbuttonActionPerformed

// display button for all result
    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
    resultdisplay.setText(event.Display());
    }//GEN-LAST:event_displaybuttonActionPerformed

// reset button
    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        resultdisplay.setText("");
        name.setText("");
        organizer.setText("");
        datentime.setText("");
        fees.setText("");
        nametosearch.setText("");
        feestosearch.setText("");
        user.setSelected(true);
        typeofevent.clearSelection();
    }//GEN-LAST:event_resetbuttonActionPerformed

// delete button by "name"
    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // check if event name input is empty 
        if ((name.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "EVENT NAME cannot be null ! Please key in again.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String delete = name.getText();
            try {
                event.Delete(delete);
                resultdisplay.setText(event.Display());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Unknown error while deleting and display the event. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_deletebuttonActionPerformed

// add button 
    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        String nametoadd = "", organizertoadd = "", datentimetoadd = "", feestoaddt = "" , typeofevent = "";
        Double feestoadd = 0.0;
        boolean error = false;

        // event name
        if ((name.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "EVENT NAME cannot be null ! PLease key in again.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            nametoadd = name.getText();

            // event organizer
            if ((organizer.getText()).isEmpty()) {
                JOptionPane.showMessageDialog(null, "EVENT ORGANIZER cannot be null ! Please key in again.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                organizertoadd = organizer.getText();

                // event date & time
                if ((datentime.getText()).isEmpty()) {
                    JOptionPane.showMessageDialog(null, "EVENT DATE & TIME cannot be null ! Please key in again.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    datentimetoadd = datentime.getText();

                    // event fees 
                    if ((fees.getText()).isEmpty()) {
                        JOptionPane.showMessageDialog(null, "EVENT FEES cannot be null ! Please key in again.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        feestoaddt = fees.getText();

                        try {
                            feestoadd = Double.parseDouble(feestoaddt);
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "EVENT FEES is not a number ! Please key in again.", "Error", JOptionPane.ERROR_MESSAGE);
                            error = true;
                        }

                        if (online.isSelected() || facetoface.isSelected()) {
                            if(online.isSelected()){
                                typeofevent = "Online Event" ;
                            }else if(facetoface.isSelected()){
                                typeofevent = "Face-to-Face Event" ;
                            }
                            if (error == false) {
                                try {
                                    // add event
                                    event.Add(nametoadd, organizertoadd, datentimetoadd, feestoadd,typeofevent);
                                    // display result
                                    resultdisplay.setText(event.Display());
                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(null, "Unknown error while adding and display the new event. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Please indicate the event is online or face-to-face.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }

                }
            }
        }
    }//GEN-LAST:event_addbuttonActionPerformed

// radiobutton for "administrator"
    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // disable register function
        registerbutton.setEnabled(false);
        // enable add & delete function
        addbutton.setEnabled(true);
        deletebutton.setEnabled(true);
        name.setEnabled(true);
        organizer.setEnabled(true);
        datentime.setEnabled(true);
        fees.setEnabled(true);
        online.setEnabled(true);
        facetoface.setEnabled(true);
    }//GEN-LAST:event_adminActionPerformed

// checkbox for "face-to-face"
    private void facetofaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facetofaceActionPerformed

    }//GEN-LAST:event_facetofaceActionPerformed

// exit button
    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        try {
            event.Save();
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "THANK YOU for using our event management system.\nHope to see you next time !", "BYE-BYE", JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_exitbuttonActionPerformed

// default for user
    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        // to disable add and delete functions
        addbutton.setEnabled(false);
        deletebutton.setEnabled(false);
        registerbutton.setEnabled(true);
        name.setEnabled(false);
        organizer.setEnabled(false);
        datentime.setEnabled(false);
        fees.setEnabled(false);
        online.setEnabled(false);
        facetoface.setEnabled(false);
    }//GEN-LAST:event_userFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new GUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JRadioButton admin;
    private javax.swing.JPanel adminpane;
    private javax.swing.JTextField datentime;
    private javax.swing.JLabel datentimelabel;
    private javax.swing.JButton deletebutton;
    private javax.swing.JScrollPane display;
    private javax.swing.JButton displaybutton;
    private javax.swing.JButton exitbutton;
    private javax.swing.JCheckBox facetoface;
    private javax.swing.JTextField fees;
    private javax.swing.JLabel feeslabel;
    private javax.swing.JLabel feeslabel1;
    private javax.swing.JTextField feestosearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel namelabel1;
    private javax.swing.JTextField nametosearch;
    private javax.swing.JCheckBox online;
    private javax.swing.JTextField organizer;
    private javax.swing.JLabel organizerlabel;
    private javax.swing.JButton registerbutton;
    private javax.swing.JButton resetbutton;
    private javax.swing.JLabel result;
    private javax.swing.JTextArea resultdisplay;
    private javax.swing.JButton searchbyfeesbutton;
    private javax.swing.JButton searchbynamebutton;
    private javax.swing.ButtonGroup typeofevent;
    private javax.swing.ButtonGroup typeofuser;
    private javax.swing.JRadioButton user;
    // End of variables declaration//GEN-END:variables
}
